version: '3.8'

services:
  # --- CAPA 1: BASE DE DATOS (Boris) ---
  mi-base-datos:
    image: borisestrada/todo-db:1.0
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - red-aplicacion

  # --- CAPA 2: BACKEND (Tu API) ---
  mi-backend:
    image: cesarvillaa/todo-backend:1.0  # 🌟 Tu imagen real de Docker Hub
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mi-base-datos 
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: todolist
    depends_on:
      - mi-base-datos
    networks:
      - red-aplicacion

  # --- CAPA 3: FRONTEND (Ismael) ---
  mi-frontend:
    image: sandiaexe/todo-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - mi-backend
    networks:
      - red-aplicacion

networks:
  red-aplicacion:
    driver: bridge
